# Generated by Django 6.0.1 on 2026-01-16 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location_type', models.CharField(max_length=50)),
                ('building', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('projector', 'Projector / Display'), ('ac', 'Air Conditioning'), ('lighting', 'Lighting'), ('furniture', 'Furniture'), ('computer', 'Computer / Hardware'), ('network', 'Network / WiFi'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('assigned_to', models.CharField(blank=True, max_length=200)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fault_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Library', max_length=100)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('max_capacity', models.IntegerField(default=100)),
                ('is_open', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Library Statuses',
            },
        ),
        migrations.CreateModel(
            name='LabStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=50)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('max_capacity', models.IntegerField(default=30)),
                ('is_available', models.BooleanField(default=True)),
                ('equipment_status', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lab Statuses',
                'unique_together': {('building', 'room_number')},
            },
        ),
    ]
