# Generated by Django 6.0.1 on 2026-01-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_created_at_profile_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverloadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('cpu', 'CPU'), ('memory', 'Memory'), ('network', 'Network'), ('occupancy', 'Occupancy')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('threshold_value', models.FloatField(default=0.0)),
                ('current_value', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='faultreport',
            name='building',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='room_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='category',
            field=models.CharField(choices=[('projector', 'Projector / Display'), ('ac', 'Air Conditioning'), ('lighting', 'Lighting'), ('furniture', 'Furniture'), ('computer', 'Computer / Hardware'), ('network', 'Network / WiFi'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('hvac', 'HVAC'), ('equipment', 'Equipment'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
