# Generated by Django 6.0.1 on 2026-01-16 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_faultreport_librarystatus_labstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='manager_type',
            field=models.CharField(blank=True, choices=[('general', 'General Manager'), ('librarian', 'Librarian'), ('it', 'IT Manager'), ('facilities', 'Facilities Manager'), ('maintenance', 'Maintenance Manager')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='RoleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('manager', 'Manager'), ('admin', 'Admin')], max_length=20)),
                ('manager_type', models.CharField(blank=True, choices=[('general', 'General Manager'), ('librarian', 'Librarian'), ('it', 'IT Manager'), ('facilities', 'Facilities Manager'), ('maintenance', 'Maintenance Manager')], max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_role_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
