# Generated by Django 6.0.1 on 2026-01-16 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_manager_type_rolerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=50)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('max_capacity', models.IntegerField(default=50)),
                ('is_available', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Classroom Statuses',
                'unique_together': {('building', 'room_number')},
            },
        ),
    ]
