# Generated by Django 6.0.1 on 2026-01-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='location',
            new_name='building',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='alert_type',
        ),
        migrations.AddField(
            model_name='lab',
            name='current_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lab',
            name='floor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
