# Generated by Django 6.0.1 on 2026-01-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_rename_location_lab_building_remove_alert_alert_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='הספרייה המרכזית', max_length=100)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('max_capacity', models.IntegerField(default=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='capacity',
            new_name='available_computers',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='is_available',
            new_name='is_open',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='floor',
            new_name='total_computers',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='title',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='building',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='current_students',
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
