# Generated by Django 6.0.1 on 2026-01-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_library_rename_capacity_lab_available_computers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='library',
            name='description',
        ),
    ]
