# Generated by Django 6.0.1 on 2026-01-10 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('current_occupancy', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('space_type', models.CharField(max_length=50)),
            ],
        ),
    ]
