# Generated by Django 6.0.1 on 2026-01-11 04:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy_percent', models.PositiveSmallIntegerField()),
                ('source', models.CharField(default='manual', max_length=100)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
