# Generated by Django 6.0.1 on 2026-01-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_alter_libraryoccupancy_occupancy_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryoccupancy',
            name='occupancy_percent',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
