# Generated by Django 6.0.1 on 2026-01-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_alter_libraryoccupancy_occupancy_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryoccupancy',
            name='captured_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
